title: 椋鸟灵note
description: 笔记合集
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
remote_theme: kitian616/jekyll-TeXt-theme
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
markdown_enhanced: true
defaults:
  - scope:
      path: ""      # 作用于所有文件
      type: "pages" # 只对普通页面生效
    values:
      layout: "default"
