title: 椋鸟灵note
description: 笔记合集
remote_theme: kaeyleo/jekyll-theme-H2O
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  math_engine: mathjax
defaults:
  - scope:
      path: ""      # 作用于所有文件
      type: "pages" # 只对普通页面生效
    values:
      layout: "default"
